"use strict";

const btn = document.querySelector(".btn");
const questionBox = document.querySelector(".question-box");

const questions = [
  "Is TypeScript similar to JavaScript?",
  "Do I need to learn TypeScript if I already know JavaScript?",
  "Are TypeScript's types mandatory?",
  "Can I use existing JavaScript libraries with TypeScript?",
  "Is TypeScript suitable for all types of projects?",
  "Explain the data types available in TypeScript",
  "Explain the behavior of arrays in TypeScript",
  "In how many ways we can declare variables in TypeScript?",
  "How you can declare a explicit variables in Typescript?",
  "How to declare a function with typed annotation in TypeScript?",
  "Describe the any type in TypeScript",
  "What are the advantages of using TypeScript?",
  "List some disadvantages of using TypeScript",
  "Explain the void type in TypeScript",
  "What is type null and its use in TypeScript?",
  "Describe the syntax for creating objects in TypeScript",
  "Can we specify the optional properties to TypeScript Object, if Yes, explain How?",
  "Explain the undefined type in TypeScript",
  "What is never type and its uses in TypeScript?",
  "Explain the working of enums in TypeScript?",
  "Is TypeScript strictly statically typed language?",
  "Is template literal supported by TypeScript?",
  "Differentiate between the .ts and .tsx file extensions given to the TyppeScript file",
  "Explain typeof operator in TypeScript and where to use it",
  "Explain the parameter destructuring in TypeScript",
  "What are interfaces in TypeScript?",
  "In what situation you should use a class and a interface?",
  "What are the differences between the classes and the interfaces in TypeScript?",
  "How you can compile a TypeScript file?",
  "How to combine multiple TypeScript files and convert them into single JavaScript file?",
  "How to compile a TypeScript file at real time while updating the file?",
  "Is it possible to call the constructor function of the base class using the child class?",
  "How to declare a class in TypeScript?",
  "How to declare a arrow function in TypeScript?",
  "How to define a function which accepts the optional parameters?",
  "How the inheritance can be used in TypeScript?",
  "What are modules in TypeScript?",
  "In how many ways you can classify Modules?",
  "What is the use of tsconfig.json file in TypeScript?",
  "What are Decorators in TypeScript?",
  "What are the different ways for controlling the visibility of member data?",
  "How to debug a TypeScript file?",
  "How to convert a .ts file into TypeScript Definition file?",
  "Is it possible to create the static classes in TypeScript?",
  "Describe anonymous functions and their uses in TypeScript?",
  "Explain the union types in TypeScript?",
  "Explain type alias in TypeScript?",
  "Is it possible to create the immutable Object properties in TypeScript?",
  "What is “in” operator and why it is used in TypeScript?",
  "Expalin conditional typing in TypeScript?",
  "Explain noImplicitAny in TypeScript",
  "Explain type inference in TypeScript",
  "Which principles of Object Oriented Programming are supported by TypeScript?",
  "In how many ways you can use the for loop in TypeScript?",
  "Explain Mixins in TypeScript",
  "What is Angular?",
  "What are components in Angular?",
  "What compilation types are there in Angular?",
  "What are the advantages of TypeScript over JavaScript?",
  "What is the purpose of structural and attribute directives?",
  "What are Angular templates and how are they used?",
  "How do you declare a service in Angular?",
  "Did you ever use state management libraries?",
  "What is lazy loading?",
  "What are Observables in Angular?",
  "Explain how change detection functions in Angular",
  "What are pipes?",
  "What are interceptors in Angular?",
  "Name the types of data binding in Angular",
  "What is metadata?",
  "What is constructor? How is it different from ngOnInit?",
  "What are the different ways to pass data between components?",
  "What are the different types of data binding in Angular?",
  "How do you handle events in Angular components?",
  "What are directives and their types in Angular?",
  "How do you create custom directives?",
  "What are services and their benefits in Angular?",
  "What are the different types of routing in Angular?",
  "Explain how to configure routing in an Angular application",
  "What is the difference between constructor and ngOnInit?",
  "What are the technologies used in Angular?",
  "Why were client-side frameworks like Angular introduced?",
  "How does an Angular application work?",
  "What is TypeScript?",
  "Write a pictorial diagram of Angular architecture?",
  "What is metadata?",
  "How is Dependency Hierarchy formed?",
  "What is the purpose of the async pipe?",
  "What is the option to choose between inline and external templates?",
  "What is the purpose of the ngFor directive?",
  "What is the purpose of the ngIf directive?",
  "What happens if you use the script tag inside the template?",
  "What are template expressions?",
  "What are template statements?",
  "What is the difference between Angular and AngularJS?",
  "What are some advantages of using Angular?",
  "How do you categorize data binding types?",
  "What is a parameterized pipe?",
  " What are custom elements?",
  "Do I need to bootstrap custom elements?",
  "How do you define typings for custom elements?",
  "Explain how custom elements work internally?",
  "How to transfer components to custom elements?",
  "What are the mapping rules between Angular components and custom elements?",
  "How are observables different from promises?",
  "What is a custom pipe?",
  "Give an example of a custom pipe?",
  "What is the difference between pure and impure pipe?",
  "What is a bootstrapping module?",
  "Explain how to use HttpClient with an example?",
  "What are lifecycle hooks in Angular?",
  "What are templates?",
  "How can you read the full response?",
  "How do you perform Error handling?",
  "What is content projection?",
  "What is the difference between PROMISE & OBSERVABLES?",
  "What do you mean by data binding?",
  "What are some disadvantages of using Angular?",
  "What do you mean by string interpolation?",
  "What are the differences between Angular decorator and annotation?",
  "What is an AOT compilation in Angular?",
  "What are the advantages of AOT?",
  "What are the three phases of AOT?",
  "What are the components in Angular?",
  "What are dynamic components?",
  "What is the purpose of base href tag?",
  "What are modules in Angular?",
  "What is DOM?",
  "What are services in Angular?",
  "What is the difference between jQuery and Angular?",
  "What is two-way data binding?",
  "What are pipes in Angular?",
  "What are observables in Angular?",
  "How do you chain pipes?",
  "What does Angular Material mean?",
  "What is RxJS?",
  "What is bootstrapping?",
  "What do you mean by dependency injection?",
  "What is the digest cycle process in Angular?",
  "What are the distinct types of Angular filters?",
  "How can one create a service in Angular?",
  "What does subscribing mean in RxJS?",
  "What is an Angular Router?",
  "What is the purpose of the common module in Angular?",
  "What are the differences between AngularJS and Angular?",
  "What is the scope in Angular?",
  "How do you create directives using CLI?",
  "What is a rule in Schematics?",
  "What is Schematics CLI?",
  "What is HttpClient, and what are its benefits?",
  "What is multicasting in Angular?",
  "What is a directive in Angular?",
  "What will happen if you do not supply a handler for an observer?",
  "What are angular elements?",
  "What is the browser support of Angular Elements?",
  "What is the role of SPA in Angular?",
  "What are Angular building blocks?",
  "Explain the MVVM architecture",
  "Describe Angular authentication and authorization",
  "What is REST?",
  "Explain Angular CLI",
  "What is schematic?",
  "Explain the different kinds of Angular directives",
  "What are the different types of compilers used in Angular?",
  "What is server-side rendering in Angular?",
  "What is Angular Universal?",
  "What are HttpInterceptors in Angular?",
  "How does one share data between components in Angular?",
  "What are the differences between Angular expressions and JavaScript expressions?",
  "What is the difference between interpolated content and the content assigned to the innerHTML property of a DOM element?",
  "What is ng-content and its purpose?",
  "What is ngcc?",
  "What is folding?",
  "What are macros?",
  "What is the state function?",
  "What is the Style()?",
  "What is NgZone?",
  "What is NoopZone?",
  "What are signals?",
  "What are the signals?",
  "What are writable signals?",
  "What are read-only signals?"
];

function getRandomQuestion() {
  const randomIndex = Math.floor(Math.random() * questions.length);
  return questions[randomIndex];
}

btn.addEventListener("click", () => {
  const randomQuestion = getRandomQuestion();
  questionBox.innerHTML = `<h2>${randomQuestion}</h2>`;
});
